if (TODAY_DATE < CHAPTER_I_DATE) {
    monogatari.script ({
        'ch1-start': [
            "show message chapterI-unreleased",
            "end"
        ],
    });
}
else {
    monogatari.script ({
        'ch1-start': [
            "show message chapterI",
            "play music calm with loop",
            "show scene birthday-beedroom with fadeIn",
            "show character brenn happy at left with fadeIn",
            "brenn Happy Birthday!!",
            "show character nota happy at center with fadeIn",
            "nota Happy Birthday Mya!",
            "show character nota neutral at center",
            "Thank you guys! I love you!",
            "brenn Hold on, let me fetch your present!",
            "hide character brenn with fadeOut",
            "<i>I can't believe they came all the way to America for my birthday.</i>",
            "<i>It doesn't make sense since they both have a full-time activity, but I'll have to let it slide for the sake of the story.</i>",
            "<i>They really hyped this birthday party up. For once, I have high expectations.</i>",
            "show character brenn happy at left with fadeIn",
            "brenn You wanted a drawing of a stickman made by me, right? I hope you didn't change your mind because it's too late now.",
            "show image stickman.png with fadeIn",
            "brenn Here you go!",
            "...",
            "show character brenn proud at left with fadeIn",
            "...",
            "<i>...</i>",
            "hide image stickman.png with fadeOut",
            "show character brenn laugh at left with fadeIn",
            "<i>Well, they made the effort to travel here, I can't expect too much.</i>",
            "<i>Still, I hope Céliane's present will make up for that.</i>",
            "show character brenn happy at left with fadeIn",
            "show character nota happy at center with fadeIn",
            "nota My turn!",
            "show character nota neutral at center with fadeIn",
            "nota Sorry Brenn, but your present sucks ass!",
            "nota Please ignore his stupid joke Mya. I got you something worth your time!",
            "nota I present to you...",
            "show image ticket.png with fadeIn",
            "nota A plane ticket!",
            "<i>A fake ticket? What??</i>",
            "hide image ticket.png with fadeOut",
            "nota Well, technically, it's not a real ticket.",
            "<i>I noticed.</i>",
            "<i>Did they really tell me it was going to be the best birthday ever, to then hand me two pieces of paper?</i>",
            "<i>There's more to it, right? There has to be.</i>",
            "nota I have yet to discover the Blessed Land of Owsseqs, where the sun shines and the harems are plentiful.",
            "show character nota happy at center with fadeIn",
            "nota When I do find it though, I'll get you there in no time!",
            "nota Can you imagine? A land of pure bliss! You can take the train at any time! Everyone speaks japanese (with subtitles for those who need them)! Harems are legal! It's the perfect land!",
            "nota Also, don't worry about meeting Rem simps there! I'll gatekeep the area! By myself!",
            "nota Take this as a promise Mya! One day, I will take you there, and we'll be the happiest people on Earth!",
            "nota I'll get you the real plane ticket when we build an airport there. I can't wait!",
            "nota Kakkoyoku kikoeru yō ni nihongo o hanasu furi o suru!",
            "<i>What?</i>",
            "show character nota neutral at center with fadeIn",
            "brenn By the way, I'm sorry but we don't have any cake for you.",
            "nota Not having a birthday cake for your birthday is surprising! You can see it as an additional birthday surprise!",
            "show character brenn laugh at left with fadeIn",
            "<i>Wow, thank you guys.</i>",
            "<i>You really OUTDID yourself.</i>",
            "show character brenn happy at left with fadeIn",
            "brenn Oh, I almost forgot the letter.",
            "brenn Apparently, someone sent you something. I don't even know if it's for you or not to be honest.",
            "brenn I hope it's not an electricity bill or something like that, I'd look pretty stupid if that were the case.",
            "show character brenn laugh at left with fadeIn",
            "brenn Hahaha!",
            "show character brenn happy at left with fadeIn",
            "<i>Hahaha.</i>",
            "<i>Well, this letter is my last hope.</i>",
            "<i>Really guys, I expected nothing. And THIS is what I get?</i>",
            "<i>You told me this was going to be the best birthday ever.</i>",
            "<i>The best birthday ever.</i>",
            "<i>Next year, I'll just play dead and reappear once I'm sure you've forgotten about it.</i>",
            "<i>Now, let's read the letter.</i>",
            "hide character brenn with fadeOut",
            "hide character nota with fadeOut",
            "nvl <br>Hello Mya Rousseau, Happy Birthday!",
            "nvl I hope you're having a good time! If not, this letter might be the one thing you need!",
            "nvl I have something for you. A hidden present, some kind of treasure hunt if you will.",
            "nvl Here are the coordinates: 43.3068° N 0.7668° W. It shouldn't be too far from where you are.",
            "nvl I look forward to meeting you.",
            "nvl Have fun!",
            "<i>That's quite creepy actually.</i>",
            "<i>Who the hell writes that kind of stuff?</i>",
            "<i>On the other hand, it's not like I've got lots of other things to do. I can't say this birthday party was super exciting.</i>",
            "<i>Looks like my two guests are already getting dressed. Did they actually plan this in advance?</i>",
            "show character brenn happy at left with fadeIn",
            "show character nota neutral at center with fadeIn",
            "We're going already?",
            "brenn What?",
            "nota ...",
            "nota Yes! We are!",
            "brenn ...",
            "brenn What?",
            "nota Let's Go!",
            "show scene outside-myas-place with fadeIn",
            "Alright!",
            "show character brenn happy at left with fadeIn",
            "show character nota neutral at center with fadeIn",
            "nota So, where are we going?",
            "All I have are those coordinates. Can you look them up?",
            "show character brenn phone at left with fadeIn",
            "brenn Sure.",
            "brenn ...",
            "brenn Alright, it's pretty far away actually. Something like a 2 hours long car ride.",
            "show character brenn happy at left with fadeIn",
            "I don't have a car though.",
            "nota Do you think we can <i>borrow</i> one? Surely, we can just take someone's car.",
            "First of all, no, we can't steal random people's cars. Second of all, how would you even enter the car without damaging it?",
            "show character brenn proud at left with fadeIn",
            "brenn Just... date the car?",
            "nota You sound like someone that never used the power of love to steal a car.",
            "show character nota laugh at center with fadeIn",
            "nota HAHAHAHA!",
            "show character brenn laugh at left with fadeIn",
            "brenn HAHAHAHAHAHAHAHAHAHAHAHAHAHA!1!!!!11!!",
            "show character nota neutral at center with fadeIn",
            "show character brenn happy at left with fadeIn",
            "brenn Hey Mya, you're a Love Expert™️, right?",
            "brenn It'll probably be faster if you're the one doing it. I'll be taking notes in silence.",
            "...",
            "Alright.",
            "<i>Oddly enough, I feel quite confident.</i>",
            "show scene #050505 with fadeIn",
            "show image engine.jpg with fadeIn",
            "stop music calm",
            "play music sax-1 with loop",
            "jump ch1-date-start"
        ],
        'ch1-date-start': [
            { 'Choice': {
                'Dialog': 'How do I handle this?',
                "A": { "Text": "Listen", "Do": "jump ch1-date-A" },
                "B": { "Text": "Talk", "Do": "jump ch1-date-B" },
                "Z": { "Text": "Guess", "Do": "jump ch1-date-Z" }
            } }
        ],
        "ch1-date-A": [
            "car ...",
            "car I wish I could find someone reliable some day...",
            "car Someone that I could feel comfortable driving around. Someone that would feel comfortable picking me as their car...",
            "car All in all, I really need something in my relationships...",
            "car <b>Reliability</b>, maybe? No, maybe that's not the word...",
            "jump ch1-date-start",
        ],
        "ch1-date-B": [
            "car ...",
            "Are you okay?",
            "car How could I be okay? I've been betrayed...",
            "car My previous master left me... Sold me to a stranger for some quick cash...",
            "car Will I ever be able to feel again? His betrayal makes me feel I'll never <b>believe</b> in anyone ever again...",
            "jump ch1-date-start",
        ],
        "ch1-date-Z": [
            { 'Input': {
                'Text': 'What does love mean to this car?',
                'Save': (input) => { monogatari.storage ({ choice: input }); },
            }},
            { 'Conditional': {
                'Condition': function () {
                    return this.storage('choice').toLowerCase() == 'trust';
                },
                'True': 'jump ch1-date-success',
                'False': 'jump ch1-date-fail'
            }},
        ],
        "ch1-date-fail": [
            "...",
            "No reaction, looks like that's not it.",
            "jump ch1-date-start"
        ],
        "ch1-date-success": [
            "...",
            "Can you trust me, maybe?",
            "car ...",
            "car Sure. I'll drive you around for a bit.",
            "car I think I love you...",
            "stop music sax-1 with fade 5",
            "jump ch1-end"
        ],
        "ch1-end": [
            "show scene outside-myas-place with fadeIn",
            "I did it!",
            "The car's willing to get us to the coordinates, and back home once we're done.",
            "Let's go!",
            "show scene #000000 with fadeIn",
            "wait 2000",
            "show scene outside-mysterious-building with fadeIn",
            "show character nota neutral at center with fadeIn",
            "...",
            "<i>Sleeping in the car wasn't the best idea, now I feel tired and my vision is still blurry.</i>",
            "nota You're alright?",
            "Of course I am. Go ahead, I'm following you.",
            "show scene inside-mysterious-building with fadeIn",
            "show particles miku-magic-slight",
            "show character nota neutral at right with fadeIn",
            "show character brenn happy at left with fadeIn",
            "play music epic with loop",
            "So, that's the mysterious location?",
            "brenn Yup. There doesn't seem to be anyone here though. That letter of yours might just be a bad joke.",
            "<i>Wait, the letter wasn't their doing?</i>",
            "wait 1000",
            "show character miku-unknown orb at center with fadeIn",
            "show particles miku-magic",
            "wait 1000",
            "show character nota scared at right with fadeIn",
            "show character brenn scared at left with fadeIn",
            "wait 1000",
            "brenn Mya what the fuck?",
            "brenn This isn't some trick of yours, is it?",
            "No it's not I swear!",
            "Aaaaaa-",
            "show particles miku-magic-intense",
            "hide character brenn with fadeOut",
            "hide character nota with fadeOut",
            "miku-unknown Be not afraid. Today is not the day that you die.",
            "miku-unknown Truth is as feeble as the foundations of this world. The truths you know at least.",
            "miku-unknown Your journey through spaces will prove to be arduous. You are worthy of my blessing, yet it is something I cannot offer you for now. You will have to do without my help.",
            "miku-unknown May we meet again, in different circumstances.",
            "play sound tp1",
            "play sound tp2",
            "show scene #000000 with fadeIn",
            "stop music epic with fade 10",
            "wait 5000",
            "hide particles",
            "vibrate 200",
            "show scene myo-throne-room with fadeIn",
            "play sound ouch",
            "wait 5000",
            "show character nota scared at center with fadeIn",
            "show character brenn scared at left with fadeIn",
            "...",
            "brenn Mya.",
            "brenn I'm never following your stupid ideas ever again.",
            "play music castle with loop",
            "show character nota neutral at center with fadeIn",
            "brenn WHAT JUST HAPPENED??",
            "I thought the letter was a surprise of yours! I just followed along!",
            "show character brenn happy at left with fadeIn",
            "You made me talk about love with a car! It just looked like a weird prank!",
            "brenn Why would I do that, that's so weird.",
            "nota Wait!",
            "nota Is this the Land of Owsseqs?",
            "show character nota happy at center with fadeIn",
            "nota Did we finally reach the heavenly abode of the sacred weebs?",
            "myo-unknown Sorry to disappoint you, but you're in my palace.",
            "show character nota scared at center with fadeIn",
            "nota Who are you?",
            "We're very sorry! We don't know how we arrived here!",
            "show character nota neutral at center with fadeIn",
            "show character myo hidden at right with fadeIn",
            "myo-unknown Oh don't worry about that. After all, I'm the one that brought you here.",
            "myo-unknown I didn't expect you to bring other people, Mya. This complicates things a little bit.",
            "myo-unknown Do you mind if I get rid of them?",
            "show character nota scared at center with fadeIn",
            "show character brenn scared at left with fadeIn",
            "nota I know you didn't ask me but I DO mind it.",
            "<i>Hold on, hold on. What's happening?</i>",
            "Well, of course I don't want you to get rid of them!",
            "show character nota happy at center with fadeIn",
            "show character brenn happy at left with fadeIn",
            "Why would you do that in the first place? I just got here with no information on what's currently happening!",
            "show character nota neutral at center with fadeIn",
            "brenn Yeah!",
            "show character brenn proud at left with fadeIn",
            "Why do you know my name? How did we get here? Who are you??",
            "brenn Yeah!",
            "myo-unknown Hm.",
            "show character brenn happy at left with fadeIn",
            "myo-unknown You see, I have very special plans for you. I'm the one that wrote that letter you know. Maybe you could show me some more trust.",
            "show character nota scared at center with fadeIn",
            "show character brenn scared at left with fadeIn",
            "myo-guard Your Excellency! We're sorry to interrupt your speech, but we're being attacked!",
            "myo-unknown Those rebels again? I thought we had the upper hand against them!",
            "myo-guard This looks like some kind of suicide mission. They lost a lot of men, but they're going to-",
            "rebel Here they are!",
            "myo-guard Your Excellency, they're here, what should we do?",
            "myo-unknown They're here for Mya! If you can't make sure she stays here, kill her.",
            "myo-guard Understood!",
            "rebel Protect Mya at all costs!",
            "rebel Please run away. We'll hold them off!",
            "nota Mya, let's go!",
            "show scene #000000 with fadeIn",
            "wait 1000",
            "rebel Please follow us. We'll get you to a safe place.",
            "stop music castle with fade 3",
            "wait 4000",
            "show scene rebel-place with fadeIn",
            "wait 1000",
            "play music sad",
            "show character nota neutral at right with fadeIn",
            "show character brenn happy at center with fadeIn",
            "brenn Phew, my legs are killing me.",
            "nota Please tell me there's no need for more running. We're at the safe place, right?",
            "rebel We are at the safe place, indeed. You may rest now. I'll fetch our leader, she'll explain everything to you.",
            "<i>Being out of breath like that really isn't pleasant.</i>",
            "<i>At least I'm sure this whole letter thing wasn't planned for my birthday. My friends wouldn't make me run like that.</i>",
            "...",
            "Any of you knows what's happening?",
            "brenn No idea. I thought it was a dream, but the pain in my legs would have woken me up if that were the case.",
            "nota This definitely isn't Owsseqs, at least this I'm sure of.",
            "nota Wait, is this an isekai?",
            "brenn Looks like it. Who's the MC?",
            "Probably not me, I didn't get the blessing.",
            "nota Me neither. A blue orb appears and we're transported in another world.",
            "show character brenn proud at center with fadeIn",
            "brenn A blue orb? All I saw was a cyan orb.",
            "nota Yes, SORRY, a CYAN orb.",
            "show character brenn happy at center with fadeIn",
            "Do you remember what the voice said right before we got transported?",
            "brenn What voice? Mine?",
            "No, when the orb started activating itself I think. There was that voice that talked about not giving us a blessing.",
            "brenn You actually heard something? For real?",
            "Yeah. I-",
            "rebel Sorry to interrupt your conversation, our leader is here.",
            "rebel Please meet our excellency: Ruler of the Third Space Boulder, Overlord of Dense Main Character, Absolute Lord of Edginess, Emolord Marie",
            "show character marie neutral at left with fadeIn",
            "marie Yo!",
            "<i>Yo?</i>",
            "marie I'm going to lore dump you real quick, and then I'll answer your questions the best I can afterwards.",
            "marie As this unnamed rebel said, I am Marie, also known as Emolord. I lead the resistance against World Ruler Myo.",
            "rebel My name's Frank...",
            "marie Myo is what you would call an 'alternate version' of you, Mya. You are indeed in an alternate world. To me, you're the one from an alternate world, but you get my point.",
            "show character brenn laugh at center with fadeIn",
            "brenn Hold on. Myo, like mayonnaise?",
            "show character brenn happy at center with fadeIn",
            "marie Yes. I advise you not to joke around when Myo can hear you. She made that joke illegal. Mayonnaise is a censored word around here.",
            "marie Myo somehow managed to become the world ruler a few years ago. There are some suspicions regarding some potential ties with the mafia, though it's never been proven.",
            "marie Apparently, world domination isn't enough to her. She started to kidnap all alternate Mya's from all different worlds. From the few informations we gathered, she seems to force her personality into the other Mya's consciousnesses.",
            "marie Her schemes would have been left unknown if it weren't for us. We rebels are unhappy with the way she rules the world.",
            "marie Well, 'ruling' might be too powerful of a world. She basically forces the people to buy and use weird merchandising based on her friends or various super niche interests.",
            "marie Unfortunately, she has access to the entire world's army. Fighting her is quite literally fighting the world, which is why we need you.",
            "marie We discovered that a Mya is required to travel through dimensions. We assumed you Mya's are superior people able to alter space and time. We have complete faith in your abilities.",
            "marie Now, we may start the QnA.",
            "brenn Why are you all emos?",
            "marie It's the rebellion's dress code. Since you have a special status in the rebellion, I won't ask you to look emo, don't worry.",
            "nota What are we supposed to do against Myo? Kill her?",
            "marie Myo is very powerful. We can't do anything without someone as powerful as her. Which is why we tried to get a Mya to our side.",
            "What if I don't want to help you?",
            "marie You don't really have much a choice. Do you want to go back to your world?",
            "Fair.",
            "marie Now, if you don't have any other question, it's time for training. I expected you to be feeble of body, but this is worst than I thought. Get to work, I want to see you as three buff rebels within three weeks.",
            "stop music sad with fade 2",
            "<i>I still had questions, but it would be too awkward to ask them now...</i>",
            "show scene #000000 with fadeIn",
            "play music montage with loop",
            "wait 1000",
            "show scene #000000 with fadeIn",
            "play sound gym",
            "wait 3000",
            "show scene gym with fadeIn",
            "show character brenn happy at center with fadeIn",
            "brenn Damn my hair's annoying during those kinds of training.",
            "You can always tie them. Do you want some help?",
            "brenn No, thanks.",
            "wait 1000",
            "play sound gym",
            "show scene #000000 with fadeIn",
            "wait 5000",
            "show scene gym with fadeIn",
            "show character brenn blush at center with fadeIn",
            "brenn ...",
            "brenn No comment.",
            "wait 1000",
            "play sound gym",
            "show scene #000000 with fadeIn",
            "wait 5000",
            "stop music montage with fade 4",
            "wait 5000",
            "show scene rebel-place with fadeIn",
            "show character brenn proud at left with fadeIn",
            "show character nota neutral at center with fadeIn",
            "show character marie neutral at right with fadeIn",
            "play music sad",
            "Alright, we did it!",
            "show character nota neutral at center with fadeIn",
            "marie Hm.",
            "marie As expected of you, you are ready.",
            "marie While you were training, we spent that time on a plan that will hopefully save the world. Please go to our lab, our scientist will explain everything to you.",
            "show scene rebel-lab with fadeIn",
            "show character brenn proud at left with fadeIn",
            "show character nota neutral at center with fadeIn",
            "wait 1000",
            "show character alex neutral at right with fadeIn",
            "alex Here you are. Please follow me.",
            "alex You know, the rebellion has been around for quite some time. We all have high hopes for you.",
            "alex Please enter the pods. We'll have to send you to another universe.",
            "alex Are you all ready?",
            "stop music sad with fade 3",
            "brenn Yup.",
            "Ready!",
            "nota Ready as well.",
            "alex Alright. Turning on the machines.",
            "play music epic with loop",
            "show particles miku-magic-slight",
            "alex To be perfectly honest, we didn't think you were as weak as you actually are.",
            "alex You definitely aren't going to be able to help us fight Myo. Marie informed me of a change of plan.",
            "show particles miku-magic",
            "alex You'll have to find stronger variants of yourselves in another world. I know this is a dick move, but I have to follow orders.",
            "show particles miku-magic-intense",
            "alex Entire worlds depend on defeating Myo. Please bring back some powerful people.",
            "alex I truly am sorry.",
            "show scene #000000 with fadeIn",
            "play sound tp1",
            "play sound tp2",
            "wait 5000",
            "stop music epic with fade 5",
            "wait 5000",
            "hide particles",
            "brenn Oooooh, I know this place!",
            "jump ch2-start"
        ]
    });
}
